# Default values for DirectorOnPrem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Update platfrom according to your Platform, Default include(GKE,Packet) and SUSE
platform: Default

server:
  release: 1.6.0-ee
  dockerSecret: directoronprem-registry-secret
  protocol: http
  url:
  httpNodePort: 30380
  httpsNodePort: 30381
  apiAuthAccessMode: unrestricted
  serverDefaultAccessGrant: true
  apiUiEnabled: true
  setupName: directoronprem
  apiAuthExternalProviderEnabled: false
  apiAuthExternalProviderConfigured:
  apiAuthInternalProviderEnabled: true
  apiAuthInternalProviderConfigured: localAuthConfig
  apiAuthEnabler:
  apiAuthGithubClientId:
  apiAuthGithubClientSecret:
  apiAuthGoogleClientId:
  apiAuthGoogleClientSecret:
  clusterDomain: cluster.local
  featureSubscriptionDisable: false
  subscriptionType: internal
  featureBillingDisable: true
  billingType: external
  featureEmailDisable: true
  senderEmailAddress:
  senderEmailPassword:
  featureDocsDisable: false
  docsUrl: https://help.mayadata.io/hc/en-us
  featureChatBotDisable: true
  slackConfigBotClientId:
  slackConfigBotClientSecret:
  slackNotificationWelcomeMessage:
  featureKialiDisable: true
  analyticsGoogleCode:
  autoconnectLocalCluster: true
  # The host URL of the AD server
  adHost:
  # The base domain of the AD server
  adDomain:
  # The port number on which the AD server is listening
  adPort: 636
  adTLS: true
  # an ADuser with read access to the AD server, someuser@domain.d1adSvcAccUser:
  adSvcAccUser:
  adSvcAccPwd:
  adNameField: givenName
  # default objectclass for users
  adUserObjectClass: person
  adGroupObjectClass: group
  # connection timeout in milliseconds
  adConnectionTimeout: 5000

mysql:
  #storageClass: openebs-jiva-default
  storageClass: standard
  storageCapacity: 50Gi

elasticSearch:
  #storageClass: openebs-hostpath
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

cassandra:
  #storageClass: openebs-hostpath
  storageClass: standard
  storageCapacity: 50Gi
  replicas: 1

mayaStore:
  #storageClass: cstor-storage-class
  storageClass: standard
  storageCapacity: 10Gi

grafana:
  #storageClass: cstor-storage-class
  storageClass: standard
  storageCapacity: 50Gi

cortex:
  replicationFactor: 1
  timeout: 5s

alertStore:
  replicationFactor: 1

ingester:
  replicas: 1

querier:
  replicas: 1

curator:
  retentionPeriod: 30
