apiVersion: v1
kind: Service
metadata:
  annotations:
  name: maya-grafana-service
spec:
  ports:
  - nodePort: 30378
    port: 3000
    protocol: TCP
    targetPort: 3000
    name: grafana
  - nodePort: 30379
    port: 8686
    protocol: TCP
    targetPort: 8686
    name: grafana-report
  selector:
    app: maya-grafana
  type: NodePort

